Repository similarweb/statusbay-helm, pull requests merged in 2020-03, with the labels that each got.

#19 Fix notifiers configuration
  templates/watcher/configmap.yaml
Labels: bug, lgtm

#20 Add PVC section to event configuration
  templates/api/configmap.yaml
Labels: enhancement

#22 Add redis
  README.md
  templates/_helpers.tpl
  templates/api/configmap.yaml
  templates/redis/redis.yaml
  templates/redis/service.yaml
  values.yaml
Labels: enhancement

#24 Add event list
  templates/api/configmap.yaml
Labels: enhancement

#27 Feature/chagne defualt dd cache
  templates/NOTES.txt
  values.yaml
Labels: enhancement, lgtm

#29 add telemetry configuration to the configmap
  templates/api/configmap.yaml
  templates/watcher/configmap.yaml
  values.yaml
Labels: enhancement, lgtm
