Repository similarweb/statusbay-helm, pull requests merged in 2020-06, with the labels that each got.

#38 Fix multiple conditions in if statement
  templates/watcher/serviceaccount.yaml
Labels: enhancement

#37 Fix ui and api service annotations missing key
  templates/api/service.yaml
  templates/ui/service.yaml
Labels: enhancement

#30 Create license
  LICENSE
Labels: documentation

#40 Feature/disable redis
  README.md
  templates/redis/redis.yaml
Labels: lgtm

#41 remove unnecessary serviceAccountName section in api and ui
  templates/api/deployment.yaml
  templates/ui/deployment.yaml
Labels: bug
