Repository similarweb/statusbay-helm, pull requests merged in 2020-02, with the labels that each got.

#1 Init chart
  Chart.yaml
  README.md
  templates/_helpers.tpl
  templates/api/configmap.yaml
  templates/api/deployment.yaml
  templates/api/service.yaml
  templates/database/database.yaml
  templates/database/service.yaml
  templates/ingress/ingress.yaml
  templates/watcher/configmap.yaml
  templates/watcher/deployment.yaml
  templates/watcher/role-readonly.yaml
  templates/watcher/rolebinding.yaml
  templates/watcher/serviceaccount.yaml
  values.yaml
Labels: enhancement, lgtm

#3 Add example of wacher yaml deployment
  watcher.yaml.example
Labels: enhancement, lgtm

#4 cluster_name in helm chart
  README.md
  templates/api/configmap.yaml
  templates/watcher/configmap.yaml
  values.yaml
  watcher.yaml.example
Labels: enhancement, lgtm

#7 Add logo image to chart.yaml
  Chart.yaml
Labels: documentation, lgtm

#6 Fix broken README.md table
  README.md
Labels: bug, documentation, lgtm

#8 Feature/add note file
  templates/NOTES.txt
Labels: documentation, lgtm

#9 Change pullPolicy images from Always to IfNotPresent
  README.md
  values.yaml
Labels: enhancement

#11 fix helm2 go template errors and chart name to match repo name
  Chart.yaml
  templates/api/configmap.yaml
  templates/api/deployment.yaml
  templates/api/service.yaml
  templates/database/database.yaml
  templates/database/service.yaml
  templates/ingress/api.yaml
  templates/ui/deployment.yaml
  templates/ui/service.yaml
  templates/watcher/configmap.yaml
  templates/watcher/deployment.yaml
  templates/watcher/role-readonly.yaml
  templates/watcher/serviceaccount.yaml
Labels: bug

#13 Change api server, remove null values from configmap
  templates/ui/deployment.yaml
  templates/watcher/configmap.yaml
Labels: bug

#15 note fix
  templates/NOTES.txt
  templates/api/configmap.yaml
Labels: enhancement

#14 change readme image name
  README.md
Labels: documentation
